// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwqezgwywxxvjufxdsjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3cWV6Z3d5d3h4dmp1Znhkc2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDI0NTYsImV4cCI6MjA2NzExODQ1Nn0.tpT0vmeRiJtAWuHmd3dmn_4P7_25iyGqof_5oYHddfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});